# Read the Docs configuration file for MkDocs projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details
# Required

version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
mkdocs:
  configuration: mkdocs.yml

# Optionally declare the Python requirements required to build your docs

python:
  install:
  - requirements: docs/requirements.txt

site_name: ACRIS
site_url: https://smartdatamodels.readthedocs.org
repo_url: https://github.com/FIWARE-Ops/brand-guide
site_description: SmartData Models
docs_dir: docs
site_dir: html
use_directory_urls: false
theme: readthedocs
markdown_extensions:
  - fenced_code

extra_css: ["https://www.fiware.org/style/fiware_readthedocs.css", "https://www.fiware.org/style/fiware_readthedocs_neutral.css"]
nav:
  - Home: index.md