site_name: ACRIS
site_url: https://smartdatamodels.readthedocs.org
repo_url: https://github.com/smart-data-models/dataModels.ACRIS
site_description: SmartData Models
docs_dir: docs
site_dir: html
use_directory_urls: false
theme: readthedocs
markdown_extensions:
  - fenced_code

extra_css: ["https://www.fiware.org/style/fiware_readthedocs.css", "https://www.fiware.org/style/fiware_readthedocs_neutral.css"]
nav:
  - Home: index.md